### PR TITLE
Inactive member organ members and fixes to installation/discharge UX

### LINKED ISSUE #166: Add "Inactive Member" as recognized organ installation function for fraternities
Fraternities can have "inactive member"s, this needs to be properly implemented.

See also GEWIS/gewisweb#1484.

### LINKED ISSUE #181: Discharging `Lid` with additional functions from organ does not discharge them from the functions
### Current behaviour

When discharging a member of an organ with a function (so installed as `Lid` and `%function%`) as `Lid`, the member is only discharged as `Lid`, keeping the member installed in the organ as `%function%`.

### Desired behaviour

This is not desired as you are either a `Lid` or `Inactief Lid` (once #166 is finished) with a function, not two separate entities. 

### Steps to reproduce

1) Create new organ installing two distinct members, one with an additional function.
2) Discharge the member with two functions as `Lid`.
3) Observe, member is still in organ, but does not appear to be (in the member overview and the checks).

### Database version

881368a

### What operating are you seeing the problem on?

_No response_

### What browsers are you seeing the problem on?

_No response_

### Other information

_No response_

### LINKED ISSUE #182: Member can be installed multiple times in organ
### Current behaviour

It is possible to install a member multiple times in the same organ with the same function.

### Desired behaviour

_No response_

### Steps to reproduce

1) Add a member to an organ.
2) Add the same member to the same organ again.

### Database version

881368a

### What operating are you seeing the problem on?

_No response_

### What browsers are you seeing the problem on?

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tomudding**
This supersedes #148.

This adds the `Inactief Lid` function to organ installation. Additionally, this fixes some UX problems that caused a lot of problems in the past.

First and foremost, installations are now sorted per member instead of per installation (date). Furthermore, when discharging a member with function `Lid`, if they had additional functions in that organ, they would technically not be a member any more but still have a function (which should not be possible), this has now been fixed by ensuring that any other functions are discharged first. Finally, it was possible to install the same member multiple times (regardless of function), this is not also not possible.

**Note:** discharging of all functions and preventing multiple installations are purely done in the front-end.

This closes #166, fixes #181, and fixes #182.

### CODE REVIEW

**Comment by tomudding** [comment]
Parity with [`GEWIS/gewisweb`](https://github.com/GEWIS/gewisweb) is ensured through GEWIS/gewisweb#1497.

File: module/Database/src/Mapper/Member.php [hunk 1]
```diff
@@ -120,7 +120,7 @@ public function find(int $lidnr): ?MemberModel
             ->where('m.lidnr = :lidnr')
             ->leftJoin('m.installations', 'r')
             ->leftJoin('m.lists', 'l')
-            ->andWhere('(r.function = \'Lid\' OR r.function IS NULL)');
+            ->andWhere('(r.function = \'Lid\' OR r.function = \'Inactief Lid\' OR r.function IS NULL)');
```
Comment (rinkp) [inline module/Database/src/Mapper/Member.php:123]: I couldn't really add this anywhere, but I think we also should add a few lines to the CheckerService since it is allowed to be installed as an inactive member and not as an active member. 

While we are at it, me actually want to ensure we don't have "Lid" when we have "Inactief Lid"

```diff
public function checkMembersHaveRoleButNotInOrgan(MeetingModel $meeting): array
    {
        $errors = [];
        $membersArray = $this->installationService->getCurrentRolesPerOrgan($meeting);

        foreach ($membersArray as $organsMembers) {
            foreach ($organsMembers as $memberRoles) {
                if (!isset($memberRoles['Lid'])) {
                    foreach ($memberRoles as $role => $installation) {
+                       if ('Inactief Lid' === $role) {
+                           continue;
+                       }
                        $errors[] = new Error\MemberHasRoleButNotInOrgan($meeting, $installation, $role);
                    }
+               } elseif (isset($memberRoles['Inactief Lid'])) {
+                   $errors[] = new Error\MemberIsInactiveInOrganButHasOtherRole($meeting, $installation, $role);
                }
            }
        }
        return $errors;
    }

```

**Review by rinkp — APPROVED** [review]
I think I tested all functionality after this PR. I do think the checker needs to be updated and I made a proposal, but wasn't sure whether I should push it, so I included it in this review.

(apart from the error that is thrown on member edits I think should be solved by df2c1e15829d9d5a9f6b7f33a36910551e3dfde4)

File: module/Database/src/Mapper/Member.php (hunk 1 above)
Comment (tomudding) [reply module/Database/src/Mapper/Member.php:123]: I think we want more types of errors in this regard. An error if a member is active and inactive (perhaps a further distinction regarding the number of roles to determine if they should be active or inactive*), an error if a member is inactive but still has a role, and an error if a member has a role but is not active (nor inactive).

```diff
     /**
-     * Checks if members still have a role in an organ (e.g. they are treasurer)
-     * but they are not a member of the organ anymore
+     * Checks if members still have a role in an organ (e.g. they are treasurer) but they are not a member of the organ
+     * anymore, or they are an inactive member.
      *
      * @param MeetingModel $meeting After which meeting do we do the validation
      *
-     * @return array Array of errors that may have occured.
+     * @return array Array of errors that may have occurred.
      */
-    public function checkMembersHaveRoleButNotInOrgan(MeetingModel $meeting): array
+    public function checkMembersHaveRolesButInactiveOrNotInOrgan(MeetingModel $meeting): array
     {
         $errors = [];
-        $membersArray = $this->installationService->getCurrentRolesPerOrgan($meeting);
+        $organs = $this->installationService->getCurrentRolesPerOrgan($meeting);

-        foreach ($membersArray as $organsMembers) {
-            foreach ($organsMembers as $memberRoles) {
-                if (!isset($memberRoles['Lid'])) {
+        foreach ($organs as $organMembers) {
+            foreach ($organMembers as $memberRoles) {
+                if (
+                    isset($memberRoles['Lid'])
+                    && isset($memberRoles['Inactief Lid'])
+                ) {
+                    // Member is active AND inactive in the same organ.
+                    $errors[] = new Error\MemberActiveAndInactiveInOrgan($meeting, /** unclear which installation should be used (maybe both?) */);
+                } elseif (
+                    !isset($memberRoles['Lid'])
+                    && isset($memberRoles['Inactief Lid'])
+                    && count($memberRoles) > 1
+                ) {
+                    // Member is inactive but still has roles.
+                    foreach ($memberRoles as $role => $installation) {
+                        $errors[] = new Error\MemberIsInactiveInOrganButHasOtherRole($meeting, $installation, $role);
+                    }
+                } elseif (
+                    !isset($memberRoles['Lid'])
+                    && !isset($memberRoles['Inactief Lid'])
+                ) {
+                    // Member is not active (nor inactive) but still has roles.
                     foreach ($memberRoles as $role => $installation) {
                         $errors[] = new Error\MemberHasRoleButNotInOrgan($meeting, $installation, $role);
                     }
                 }
             }
         }
+
         return $errors;
     }
```

*: With additional roles assume that inactive state is incorrect. If there are no additional roles assume active state is incorrect. Like this:

```php
// ...
if (
    isset($memberRoles['Lid'])
    && isset($memberRoles['Inactief Lid'])
) {
    // Member is active AND inactive in the same organ.
    if (count($memberRoles > 2)) {
        $errors[] = new Error\MemberActiveWithRolesAndInactiveInOrgan($meeting, $memberRoles['Inactief Lid']);
    } else {
        $errors[] = new Error\MemberActiveAndInactiveInOrgan($meeting, $memberRoles['Lid']);
    }
} elseif (
    !isset($memberRoles['Lid'])
    && isset($memberRoles['Inactief Lid'])
    && count($memberRoles) > 1
) {
// ...
```
